import type { AppRouteMeta, ModuleManifest, PlatformManifest } from "@rinjani/shared-types";

export const platforms: PlatformManifest[] = [
  {
    id: "portal",
    label: "Portal",
    basePath: "/",
    defaultRoute: "/",
    description: "Entry hub for profile, notifications, surveys, search, and admin features.",
    iconKey: "workspace",
    order: 1,
    visibleTo: ["Admin", "User"],
  },
  {
    id: "talent",
    label: "Talent",
    switcherLabel: "Rinjani Talent",
    basePath: "/talent",
    defaultRoute: "/talent",
    description: "Talent journeys, talent management, job tender, and 360 assessment.",
    iconKey: "users",
    order: 2,
    visibleTo: ["Admin", "User"],
  },
  {
    id: "performance",
    label: "Performance",
    switcherLabel: "Rinjani Performance",
    basePath: "/performance",
    defaultRoute: "/performance/my-kpi",
    description: "KPI planning, monitoring, and headquarter dashboards.",
    iconKey: "trophy",
    order: 3,
    visibleTo: ["Admin", "User"],
  },
];

export const sidebarModules: ModuleManifest[] = [
  { id: "portal-dashboard", label: "Dashboard", routePath: "/", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Default landing page and information hub.", iconKey: "grid", order: 1 },
  { id: "portal-my-profile", label: "My Profile", routePath: "/my-profile", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Employee self-service profile.", iconKey: "users", order: 2 },
  { id: "portal-survey", label: "Survey", routePath: "/survey", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Ongoing and historical employee surveys.", iconKey: "clipboard", order: 3 },
  { id: "portal-policy", label: "HC Digi Policy", routePath: "/hc-policy", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Policy library and support documentation.", iconKey: "file", order: 4 },
  { id: "portal-analytics", label: "Analytics", routePath: "/analytics", parentPlatformId: "portal", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Portal-wide analytics dashboard.", iconKey: "analytics", order: 5 },
  { id: "portal-mail", label: "Mail Management", routePath: "/mail", parentPlatformId: "portal", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Message templates and email administration.", iconKey: "mail", order: 6 },
  { id: "portal-offboarding", label: "Offboarding", routePath: "/offboarding", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Administration", description: "Offboarding process tracking.", iconKey: "briefcase", order: 7 },
  { id: "portal-settings", label: "Settings", routePath: "/settings", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Administration", description: "CMS, user management, notifications, onboarding, and survey administration.", iconKey: "settings", order: 8 },

  { id: "talent-home", label: "Talent Home", routePath: "/talent", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Talent dashboard and alerts.", iconKey: "grid", order: 1 },
  { id: "talent-career-aspiration", label: "Career Aspiration", routePath: "/talent/career-aspiration", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Career path and aspiration flow.", iconKey: "target", order: 2 },
  { id: "talent-idp", label: "Development Plan", routePath: "/talent/idp", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Individual development plan routes.", iconKey: "clipboard", order: 3 },
  { id: "talent-360", label: "360 Assessment", routePath: "/talent/360-assessment", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Assessment list and reports.", iconKey: "analytics", order: 4 },
  { id: "talent-job-tender", label: "Job Tender Marketplace", routePath: "/talent/explore", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Explore jobs and application routes.", iconKey: "briefcase", order: 5 },
  { id: "talent-pool", label: "Talent Pool", routePath: "/talent/talent-pool", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Talent pool and profiling.", iconKey: "users", order: 6 },
  { id: "talent-succession", label: "Succession Planning", routePath: "/talent/succession-planning", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Succession dashboards and candidates.", iconKey: "git", order: 7 },
  { id: "talent-classification", label: "Talent Classification", routePath: "/talent/talent-mapping", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "9-box classification and calibration.", iconKey: "grid", order: 8 },
  { id: "talent-review", label: "Talent Review", routePath: "/talent/talent-review", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Talent review pages.", iconKey: "file", order: 9 },
  { id: "talent-supervisor", label: "Supervisor Portal", routePath: "/talent/supervisor-portal", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Supervisor team and proposal views.", iconKey: "users", order: 10 },
  { id: "talent-committee", label: "Talent Committee Portal", routePath: "/talent/talent-committee", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Talent committee review, sessions, and decisions.", iconKey: "users", order: 11 },
  { id: "talent-job-admin", label: "Job Tender Headquarters", routePath: "/talent/admin/job-tender", parentPlatformId: "talent", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Job tender administration.", iconKey: "briefcase", order: 12 },
  { id: "talent-idp-admin", label: "IDP Headquarters", routePath: "/talent/admin/idp", parentPlatformId: "talent", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "IDP administration routes.", iconKey: "clipboard", order: 13 },
  { id: "talent-org", label: "Organization Management", routePath: "/talent/org-management", parentPlatformId: "talent", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Organization module placeholder.", iconKey: "settings", order: 14 },

  { id: "performance-my-kpi", label: "My KPI", routePath: "/performance/my-kpi", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "Individual KPI dashboard.", iconKey: "trophy", order: 1 },
  { id: "performance-my-team", label: "My Team KPI", routePath: "/performance/my-team-kpi", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "Manager KPI monitoring and planning.", iconKey: "users", order: 2 },
  { id: "performance-library", label: "KPI Library", routePath: "/performance/kpi-library", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "Standard KPI catalog.", iconKey: "clipboard", order: 3 },
  { id: "performance-tree", label: "KPI Tree", routePath: "/performance/kpi-tree", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "KPI alignment visualization.", iconKey: "git", order: 4 },
  { id: "performance-hq", label: "KPI Headquarter", routePath: "/performance/kpi-headquarter", parentPlatformId: "performance", visibleTo: ["Admin"], sidebarGroup: "Performance", description: "Headquarter metrics and configuration.", iconKey: "analytics", order: 5 },
];

export const routeMeta: AppRouteMeta[] = [
  { path: "/", pageTitle: "Portal Dashboard", breadcrumbLabel: "Dashboard", platformId: "portal", moduleId: "portal-dashboard", searchScope: "platform" },
  { path: "/my-profile", pageTitle: "My Profile", breadcrumbLabel: "My Profile", platformId: "portal", moduleId: "portal-my-profile", searchScope: "platform" },
  { path: "/survey", pageTitle: "Survey", breadcrumbLabel: "Survey", platformId: "portal", moduleId: "portal-survey", searchScope: "platform" },
  { path: "/survey/take/:surveyId", pageTitle: "Take Survey", breadcrumbLabel: "Take Survey", platformId: "portal", moduleId: "portal-survey", hidden: true, searchScope: "module" },
  { path: "/survey/analytics/:surveyId", pageTitle: "Survey Analytics", breadcrumbLabel: "Survey Analytics", platformId: "portal", moduleId: "portal-survey", hidden: true, searchScope: "module" },
  { path: "/survey/management", pageTitle: "Survey Management", breadcrumbLabel: "Survey Management", platformId: "portal", moduleId: "portal-settings", hidden: true, searchScope: "module" },
  { path: "/hc-policy", pageTitle: "HC Digi Policy", breadcrumbLabel: "HC Digi Policy", platformId: "portal", moduleId: "portal-policy", searchScope: "global" },
  { path: "/employee-profile/:email", pageTitle: "Employee Profile", breadcrumbLabel: "Employee Profile", platformId: "portal", moduleId: "portal-my-profile", hidden: true, searchScope: "module" },
  { path: "/analytics", pageTitle: "Analytics", breadcrumbLabel: "Analytics", platformId: "portal", moduleId: "portal-analytics", searchScope: "platform" },
  { path: "/mail", pageTitle: "Mail Management", breadcrumbLabel: "Mail", platformId: "portal", moduleId: "portal-mail", searchScope: "platform" },
  { path: "/offboarding", pageTitle: "Offboarding", breadcrumbLabel: "Offboarding", platformId: "portal", moduleId: "portal-offboarding", searchScope: "platform" },
  { path: "/settings", pageTitle: "Settings", breadcrumbLabel: "Settings", platformId: "portal", moduleId: "portal-settings", searchScope: "platform" },
  { path: "/talent", pageTitle: "Talent Home", breadcrumbLabel: "Talent Home", platformId: "talent", moduleId: "talent-home", searchScope: "platform" },
  { path: "/talent/career-aspiration", pageTitle: "Career Aspiration", breadcrumbLabel: "Career Aspiration", platformId: "talent", moduleId: "talent-career-aspiration", searchScope: "platform" },
  { path: "/talent/idp", pageTitle: "Development Plan", breadcrumbLabel: "Development Plan", platformId: "talent", moduleId: "talent-idp", searchScope: "platform" },
  { path: "/talent/explore", pageTitle: "Job Tender Marketplace", breadcrumbLabel: "Job Tender", platformId: "talent", moduleId: "talent-job-tender", searchScope: "platform" },
  { path: "/talent/talent-pool", pageTitle: "Talent Pool", breadcrumbLabel: "Talent Pool", platformId: "talent", moduleId: "talent-pool", searchScope: "platform" },
  { path: "/talent/succession-planning", pageTitle: "Succession Planning", breadcrumbLabel: "Succession Planning", platformId: "talent", moduleId: "talent-succession", searchScope: "platform" },
  { path: "/talent/talent-mapping", pageTitle: "Talent Classification", breadcrumbLabel: "Talent Classification", platformId: "talent", moduleId: "talent-classification", searchScope: "platform" },
  { path: "/talent/talent-review", pageTitle: "Talent Review", breadcrumbLabel: "Talent Review", platformId: "talent", moduleId: "talent-review", searchScope: "platform" },
  { path: "/performance/my-kpi", pageTitle: "My KPI", breadcrumbLabel: "My KPI", platformId: "performance", moduleId: "performance-my-kpi", searchScope: "platform" },
];
