import type { PerformancePrototypeState } from './types';

export const initialPerformancePrototypeState: PerformancePrototypeState = {
  persona: 'KARYAWAN',
  employees: [
    {
      employeeNumber: '260102',
      displayName: 'Binavia Wardhani',
      positionTitle: 'Group Head HC Planning & Analytics',
      organizationName: 'Direktorat Human Capital',
      bandJabatan: 'Madya',
      jobType: 'STRUKTURAL',
      positionMasterVariantId: 'PMV-HC-GH-001',
      directSupervisorId: '260101',
    },
    {
      employeeNumber: '260101',
      displayName: 'Dimas Sayyid',
      positionTitle: 'VP HC Strategy',
      organizationName: 'Direktorat Human Capital',
      bandJabatan: 'Utama',
      jobType: 'STRUKTURAL',
      positionMasterVariantId: 'PMV-HC-VP-001',
    },
    {
      employeeNumber: '260900',
      displayName: 'Nadira Paramitha',
      positionTitle: 'HC Admin HO',
      organizationName: 'Performance Management HO',
      bandJabatan: 'Madya',
      jobType: 'STRUKTURAL',
      positionMasterVariantId: 'PMV-HO-ADMIN-001',
    },
  ],
  period: {
    id: 'PERF-2026',
    year: 2026,
    phase: 'PLANNING',
    planningDeadline: '2026-02-28',
    monitoringDeadline: '2026-04-10',
    status: 'OPEN',
  },
  bandFormula: {
    id: 'BKF-MADYA-STR-2026',
    bandJabatan: 'Madya',
    jobType: 'STRUKTURAL',
    kpiBersamaWeight: 40,
    kpiUnitWeight: 60,
    year: 2026,
    effectiveFrom: '2026-01-01',
  },
  ruleConfig: {
    id: 'RULE-2026',
    year: 2026,
    minItemsPerType: 3,
    maxItemsPerType: null,
    minWeightPerItem: 5,
    maxWeightPerItem: 40,
    globalCapType: 'CAPPED_110',
    categoryBasedScoringEnabled: true,
  },
  deadlineConfig: {
    id: 'DL-MON-2026',
    phase: 'MONITORING',
    deadlineDate: '2026-04-10',
    penaltyType: 'LATE_FLAG',
    extensionMaxDays: 10,
    extensionMaxRequests: 1,
    autoApproveTimeoutDays: 5,
  },
  ratingScale: {
    id: 'RATING-2026',
    method: 'FIXED',
    ranges: [
      { label: 'Outstanding', min: 4.5, max: 5 },
      { label: 'Excellent', min: 3.5, max: 4.49 },
      { label: 'Successful', min: 3, max: 3.49 },
      { label: 'Need Improvement', min: 1, max: 2.99 },
    ],
  },
  mutationPolicy: {
    id: 'MUT-2026',
    year: 2026,
    proRataMethod: 'WEIGHTED_AVERAGE',
    minimumDurationMonths: 3,
    cutoffDay: 15,
    carryOverEnabled: true,
  },
  kpiItems: [
    {
      id: 'KPI-B-001',
      title: 'Customer Satisfaction Index (CSI)',
      kpiType: 'BERSAMA',
      source: 'ADMIN_UPLOAD',
      targetType: 'FIXED',
      targetValue: '4.2',
      targetUnit: 'Skala 1-5',
      polarity: 'POSITIVE',
      monitoringPeriod: 'ANNUAL',
      capType: 'CAPPED_100',
      formula: 'Skor survey pelanggan tahunan',
      lockedAttributes: ['title', 'formula', 'capType'],
      approvalStatus: 'APPROVED',
      weight: 25,
      ownerEmployeeNumber: '260102',
    },
    {
      id: 'KPI-B-002',
      title: 'Revenue Growth',
      kpiType: 'BERSAMA',
      source: 'ADMIN_UPLOAD',
      targetType: 'FIXED',
      targetValue: '12%',
      targetUnit: '%',
      polarity: 'POSITIVE',
      monitoringPeriod: 'ANNUAL',
      capType: 'NO_CAP',
      lockedAttributes: ['title', 'formula'],
      approvalStatus: 'APPROVED',
      weight: 15,
      ownerEmployeeNumber: '260102',
    },
    {
      id: 'KPI-U-001',
      title: 'HC Analytics Dashboard Completion',
      kpiType: 'UNIT',
      source: 'LIBRARY',
      targetType: 'PROGRESSIVE',
      targetValue: '100%',
      targetUnit: '%',
      polarity: 'POSITIVE',
      monitoringPeriod: 'QUARTERLY',
      capType: 'CAPPED_100',
      formula: 'Dashboard selesai / dashboard target',
      lockedAttributes: ['title', 'formula'],
      approvalStatus: 'DRAFT',
      weight: 20,
      ownerEmployeeNumber: '260102',
    },
    {
      id: 'KPI-U-002',
      title: 'Workforce Planning Accuracy',
      kpiType: 'UNIT',
      source: 'LIBRARY',
      targetType: 'FIXED',
      targetValue: '90%',
      targetUnit: '%',
      polarity: 'POSITIVE',
      monitoringPeriod: 'SEMESTER',
      capType: 'NO_CAP',
      approvalStatus: 'DRAFT',
      weight: 15,
      ownerEmployeeNumber: '260102',
    },
    {
      id: 'KPI-U-003',
      title: 'Time-to-Fill Critical Positions',
      kpiType: 'UNIT',
      source: 'CUSTOM',
      targetType: 'FIXED',
      targetValue: '45',
      targetUnit: 'Hari',
      polarity: 'NEGATIVE',
      monitoringPeriod: 'QUARTERLY',
      capType: 'CAPPED_100',
      formula: 'Target hari / realisasi hari',
      lockedAttributes: [],
      approvalStatus: 'DRAFT',
      weight: 15,
      ownerEmployeeNumber: '260102',
    },
    {
      id: 'KPI-U-004',
      title: 'HC Policy Compliance Rate',
      kpiType: 'UNIT',
      source: 'CASCADED',
      targetType: 'FIXED',
      targetValue: '95%',
      targetUnit: '%',
      polarity: 'POSITIVE',
      monitoringPeriod: 'ANNUAL',
      capType: 'CAPPED_100',
      lockedAttributes: ['title'],
      approvalStatus: 'ALLOCATED',
      weight: 10,
      ownerEmployeeNumber: '260102',
    },
  ],
  ownerships: [],
  realizations: [
    {
      id: 'REAL-Q1-001',
      kpiItemId: 'KPI-U-001',
      employeeNumber: '260102',
      period: 'Q1',
      actualValue: '85%',
      progressNote: 'Dashboard core views delivered; adoption training still in progress.',
      evidence: [
        {
          id: 'EVD-001',
          type: 'LINK',
          label: 'Dashboard release note',
          value: 'https://injourney.example/performance/dashboard-q1',
          uploadedBy: '260102',
        },
      ],
      lateFlag: true,
      status: 'SUBMITTED',
    },
  ],
  scores: [
    {
      id: 'SCORE-001',
      kpiItemId: 'KPI-U-001',
      achievementPct: 85,
      performanceIndex: 3.4,
      weightedScore: 0.68,
      capApplied: true,
      scoringRuleVersion: '2026.1',
      year: 2026,
    },
  ],
  extensionRequests: [
    {
      id: 'EXT-001',
      performancePeriodId: 'PERF-2026',
      requestedBy: '260102',
      reason: 'Evidence from vendor delivery report is delayed.',
      requestedDays: 3,
      status: 'PENDING',
    },
  ],
  adjustmentRequests: [
    {
      id: 'ADJ-001',
      requestedBy: '260102',
      type: 'WEIGHT_CHANGE',
      kpiItemId: 'KPI-U-003',
      justification: 'Project prioritas baru dari Direksi',
      oldValue: '15%',
      newValue: '20%',
      status: 'PENDING',
      slaDeadline: '2026-04-10',
    },
  ],
  librarySubmissions: [
    {
      id: 'LIB-SUB-001',
      title: 'Digital Workforce Adoption Rate',
      submittedBy: '260102',
      status: 'SUBMITTED',
      similarityPct: 74,
      validationSla: '2026-04-12',
      approvalSla: '2026-04-19',
      capType: 'CAPPED_110',
      lockedAttributes: ['formula', 'capType'],
    },
  ],
  treeWarnings: [
    {
      id: 'WARN-001',
      label: 'WEIGHT_MISMATCH',
      kpiTitle: 'HC Analytics Dashboard Completion',
      severity: 'HIGH',
      owner: 'Binavia Wardhani',
    },
    {
      id: 'WARN-002',
      label: 'UNALLOCATED',
      kpiTitle: 'Customer Journey Digitization',
      severity: 'MEDIUM',
      owner: 'Direktorat Human Capital',
    },
  ],
  bulkUploadDryRun: {
    id: 'BULK-DRY-001',
    mode: 'CREATE_ONLY',
    totalRows: 18,
    validRows: 15,
    rejectedRows: 3,
    message: 'Create-only dry run: 15 KPI rows can be created; 3 rejected because matching KPI IDs already exist.',
  },
  auditLog: [
    {
      id: 'AUD-001',
      action: 'SAVE_HQ_POLICY',
      actorRole: 'HC_ADMIN_HO',
      actorName: 'Nadira Paramitha',
      target: 'BandKpiFormula Madya 2026',
      entityType: 'HQ_CONFIG',
      createdAt: '2026-04-07T08:00:00.000Z',
      note: 'Canonical DIP policy set Madya Struktural to 40/60.',
      oldValue: '45/55',
      newValue: '40/60',
    },
  ],
  forceFinalized: false,
  yearClosed: false,
  lastMessage: 'Prototype++ state initialized from canonical DIP guidance.',
};
